spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8888
      name: eureka
      label: dev
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/